name: Docker Build Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      id: build
      run: |
        docker build . --file Dockerfile --tag test-image
        
        echo "✅ Docker image built successfully"
        echo "Image size:"
        docker images test-image --format "table {{.Size}}"

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master 
      with:
        image-ref: 'test-image'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'  
        severity: 'CRITICAL,HIGH'  
    # - name: Upload scan results
    #   uses: github/codeql-action/upload-sarif@v3  # نسخه v3 جدیدتر
    #   with:
    #     sarif_file: 'trivy-results.sarif'
    #     category: 'trivy-scan'
        
    - name: Clean up
      run: |
        docker rmi test-image

